config/routes.rb
Rails.application.routes.draw do
  get 'users/show'

  devise_for :users

  resources :tracks do
    resources :reviews
    member do
      put "like" => "tracks#upvote"
      put "dislike" => "tracks#downvote"
    end
  end

  resources :users
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :tracks


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :track
  belongs_to :user

end

app/models/track.rb
class Track < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :genre
  has_many :reviews
  belongs_to :type

  validates_uniqueness_of :title, :case_sensitive => false

  has_attached_file :mp3
  validates_attachment :mp3, :content_type => { :content_type => ["audio/mpeg", "audio/mp3"] }, :file_name => { :matches => [/mp3\Z/] }


# mount_uploader :mp3, AudioUploader

  def self.search(search)
    if search
      where(["lower(title) LIKE ?", "%#{search}%"]).order("created_at DESC")
    else
      all
    end
  end
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :tracks
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter

  has_many :tracks
  has_many :reviews

  validates :username, presence: true

  has_attached_file :user_img, styles: { :user_show => "300x300>", :user_page => "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :user_img, content_type: /\Aimage\/.*\z/

  mount_uploader :image, ImageUploader


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :first_name, :last_name, :image]
    account_attr = [:username, :image]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: account_attr

  end

  def after_sign_in_path_for(resource)
  tracks_path
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_track
  before_action :find_review, only: [:edit, :update, :destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.track_id = @track.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to track_path(@track)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @review.save(review_params)
      redirect_to track_path(@track)
    else
      render 'edit'
    end 
  end

  def destroy
    @review.destroy
    redirect_to track_path(@track)
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

  def find_track
      @track = Track.find(params[:track_id])
  end

  def find_review
    @review = Review.find(params[:id])
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :find_track, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  def index
    if params[:genre].blank?
      @tracks = Track.search(params[:search]).order("created_at DESC")
    else
      @genre_id = Genre.find_by(name: params[:genre]).id
      @tracks = Track.where(:genre_id => @genre_id).order("created_at DESC")
    end
  end

  def new
    #associates the new path to current user
    @track = current_user.tracks.build
    #gets all existing genres from table with all existing params, similar to a loop thru
    @genres = Genre.all.map{ |g| [g.name, g.id]}

    @types = Type.all.map{ |t| [t.name, t.id]}
  end

  def show
    # first finds track by id (code is in private find_track method)
    if @track.reviews.blank?
      @average_review = 0
    else
      @average_review = @track.reviews.average(:rating).round(2)
    end
  end

  def create
    #initialises the create for the current user
    @track = current_user.tracks.build(track_params)

    # associates and passes in the selected genre param (id) into tracks table
    @track.genre_id = params[:genre_id]

    # associates and passes in the selected type param (id) into tracks table
    @track.type_id = params[:type_id]

    if @track.save
      redirect_to root_path
    else
      render 'new'
    end

  end # --- end CREATE

  def edit
    #gets all existing genres from table with all existing params, similar to a loop thru
    @genres = Genre.all.map{ |g| [g.name, g.id]}
  end

  def update

    if @track.update(track_params)
      redirect_to track_path(@track)
    else
      render 'edit'
    end
  end

  def destroy
    @track.destroy
    redirect_to root_path
  end

  def upvote
    @track.upvote_from current_user
    redirect_to tracks_path
  end

  def downvote
    @track.downvote_from current_user
    redirect_to tracks_path
  end

private

  def track_params
    params.require(:track).permit(:title, :description, :genre_id, :price, :mp3)
  end

  def find_track
    @track = Track.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit]

  def edit
  end

  def show
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samplrfy - Royalty Free Audio Sample Library</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Audiowide|Cairo:200,400|Comfortaa:300,400,700|PT+Sans:400|Quicksand:300,400,500|Montserrat:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,800" rel="stylesheet">
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="jquery.jplayer.min.js"></script>
    <script src="jplayer.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-default nav-down">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Samplrfy", root_path, class: 'navbar-brand' %>
      </div>

    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown profile_dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
            <% if current_user.image == nil %>
              <i class="fa fa-user-circle-o fa-2x destroy_icon" aria-hidden="true"></i>
              <span class="caret"></span>
              <% else %>
                <%= image_tag current_user.image , class: "navbar_profile_image" %>
              <span class="caret"></span>
              <% end %>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li class="text-right"><%= link_to "My Library", user_path(current_user) %></li>
            <li class="text-right"><%= link_to "PlayView" %></li>
            <li class="text-right"><%= link_to "Profile Settings", edit_user_registration_path %></li>
            <li class="text-right"><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
          </ul>
        </li>

      <% else %>
      <li class="cred_line"><%= link_to "Log In", new_user_session_path %></li>
      <li><button class="btn sign_up_btn"><%= link_to "Join", new_user_registration_path %></button></li>
      <% end %>

    </ul>

    <ul class="nav navbar-nav navbar-right upload_ul">
      <% if user_signed_in? %>
      <li><button class="btn upload_nav_button"><%= link_to "Upload", new_track_path %></button></li>
      <% end %>
    </ul>

    <ul class="nav navbar-nav navbar-right bunch">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Library", tracks_path %></li>
      <li><%= link_to root_path, class: "cart_li" do %>
        <i class="fa fa-inbox" aria-hidden="true"></i>
        <% end %>
      </li>
    </ul>

    <ul class="nav navbar-nav">
      <li>
        <%= form_tag tracks_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search],  placeholder: "Search...", class: "search_bar" %>
          <%= submit_tag "Go", class: "search_bar_submit" %>
        <% end %>
      </li>

    </ul>

    </div>
  </nav>

  <% if notice %>
  <div id="notice_wrapper">
    <p class="notice text-center"><%= notice %></p>
  </div>
  <% elsif alert %>
  <div id="notice_wrapper">
    <p class="alert text-center"><%= alert %></p>
  </div>
  <% end %>


    <div class="container-fluid">
      <%= yield %>
    </div>

    <div class="custom-notice">
      <div class="row">
        <div class="col-xs-1"><i class="fa fa-exclamation-circle fa-2x warning-icon" aria-hidden="true"></i></div>
        <div class="col-xs-10">
          <h6 class="custom-notice-text">This site is still under construction for tablet and mobile devices.</h6>
        </div>
        <div class="col-xs-1"><i class="fa fa-times close-icon" aria-hidden="true"></i></div>
      </div>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container-fluid video-cover"></div>

<video src="https://res.cloudinary.com/dbe5xk4jk/video/upload/v1516275677/Triple_Video_2_m2vlll.mp4" autoplay=“true” loop type="video/mp4">
</video>

<div class="container-fluid root_index_container">
  <% if user_signed_in? %>
    <div class="index_int_container">
      <div class="row">
        <div class="col-xs-12">
          <h1 class="text-center index_title">The World of Royalty Free Audio.</h1>
          <h4 class="text-center index_desc">The Professional Audio Library free for Personal and Commercial Use.</h4>
          <div class="text-center"><%= form_tag tracks_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search],  placeholder: "Search by Track Name", class: "search_bar_index" %>
            <%= submit_tag "Search", class: "search_bar_submit_index" %>
          <% end %>
        </div>
        <div class="text-center explore_advanced">
          <h6>Advanced Search (Currently Unavailable)</h6>
        </div>
        </div>
      </div>
    </div>
  <% else %>
  <div class="index_int_container">
    <div class="row">
      <div class="col-xs-12">
        <h1 class="text-center index_title">The World of Royalty Free Audio.</h1>
        <h4 class="text-center index_desc">The Professional Audio Library free for Personal and Commercial Use.</h4>
        <div class="text-center"><%= form_tag tracks_path, :method => 'get' do %>
          <%= text_field_tag :search, params[:search],  placeholder: "Search by Track Name", class: "search_bar_index" %>
          <%= submit_tag "Search", class: "search_bar_submit_index" %>
        <% end %>
      </div>
      <div class="text-center explore_advanced">
        <h6>Advanced Search (Currently Unavailable)</h6>
      </div>
      </div>
    </div>
  </div>
  <% end %>


  <div class="genre_select_container">
    <div class="row genre_select_row genres_home">
      <div class="col-xs-2 genre_select_col">
        <div class="text-center">
          <h4>Select by Genre</h4>
        </div>
      </div>

      <div class="col-xs-10">
        <ul class="genre_ul">
          <li class="genre_li genre_li_home"><h5><%= link_to "All", tracks_path %></h5></li>
              <% Genre.all.each do |genre| %>
                <li class="<%= 'highlight' if params[:genre] == genre.name %> text-center genre_li genre_li_home"><h5><%= link_to genre.name, tracks_path(genre: genre.name), class: "link" %></h5></li>
              <% end %>
        </ul>
      </div>
    </div><!-- / genre_select_row -->
  </div>

  <div class="down_arrow">
    <div class="text-center">
  <%= image_tag 'arrow_down.gif', :alt => 'logo' %>
    </div>
  </div>

</div><!-- end root_index_container -->

app/views/reviews/_review.html.erb
<div class="row full_review_row">
  <div class="col-xs-1">
  <%= link_to image_tag review.user.image, class: "audio_panel_profile_image" %>
  </div>
  <div class="col-xs-11">
    <div class="row">
      <div class="col-xs-3">
        <strong><h5><%= review.user.username %></h5></strong>
      </div>
      <div class="col-xs-3">
        <h5 class="review_time_ago"><%= "#{time_ago_in_words(review.created_at).gsub('about ','')} ago" %></h5>
      </div>
      <% if user_signed_in? %>
        <% if review.user_id == current_user.id %>
            <div class="col-xs-3">
              <h6><%= link_to "Edit", edit_track_review_path(review.track, review), class: "btn edit_review_btn" %></h6>
            </div>
            <div class="col-xs-3">
                <h6><%= link_to "Delete", track_review_path(review.track, review), method: :delete, data: { confirm: "Are you sure you want to delete this comment?"}, class: "btn remove_review_btn" %></h6>
            </div>
        <% end %>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xs-3">
        <div class="review-rating" data-score="<%= review.rating %>"></div>
      </div>
      <div class="col-xs-9 review_comment_text">
          <h5><%= review.comment %></h5>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="col-sm-10 col-md-offset-1">
  <div class="container-fluid login_panel">
    <h1>New Review</h1>

    <%= render 'form' %>
  </div>
</div>

app/views/tracks/index.html.erb
<div class="container-fluid root_index_container">

  <div class="genre_select_container">
    <div class="row genre_select_row">
      <div class="col-xs-2 genre_select_col">
        <div class="text-center">
          <h4>Select by Genre</h4>
        </div>
      </div>

      <div class="col-xs-10">
        <ul class="genre_ul">
          <li class="genre_li"><h5><%= link_to "All", tracks_path %></h5></li>
              <% Genre.all.each do |genre| %>
                <li class="<%= 'highlight' if params[:genre] == genre.name %> text-center genre_li"><h5><%= link_to genre.name, tracks_path(genre: genre.name), class: "link" %></h5></li>
              <% end %>
        </ul>
      </div>
    </div><!-- / genre_select_row -->
  </div>

  <div class="row">
    <div class="col-xs-4"></div>
    <div class="col-xs-4">
      <ul class="nav nav-pills">
        <li class="active"><a data-toggle="pill" href="#newest">Newest</a></li>
        <li><a data-toggle="pill" href="#trending">Trending</a></li>
    </ul>
    </div>
    <div class="col-xs-4">
    </div>
    </div>

  <div class="tab-content">
    <div id="newest" class="tab-pane fade in active">
      <div class="audio_panels_display">
        <div class="row results_found_row">
          <div class="text-center"><h5><i><%= @tracks.count %> results found</i></h5></div>
        </div>
      <!-- AUDIO PANELS -->
      <% if @tracks.count == 0 %>
        <div class="row result_notice">
          <h3 class="text-center">Sorry! There are currently no new samples in this genre.</h3>
          <div class="text-center"><%= link_to "Add Track for this Genre", new_track_path, class: "btn add_track" %></div>
        </div>
        <% else %>
      <% @tracks.each do |track| %>
      <div class="col-md-4 text-center">
        <!-- AUDIO PANEL -->
        <div class="audio_panel">
          <!-- TOP AUDIO PANEL ROW - Genre < > Likes -->
          <div class="row top_audio_panel_row">
            <div class="col-xs-4 text-left genre_col">
              <button class="btn text-left genre_tag"><%= track.genre.name.upcase %></button>
            </div>
            <div class="col-xs-4 time_ago">
              <p class="text-center"><%= "#{time_ago_in_words(track.created_at).gsub('about ','')} ago" %></p>
            </div>
            <div class="col-xs-4">
              <div class="text-right like_icon">
                <%= link_to like_track_path(track), class: "like", method: :put do %>
                  <div class="col-xs-8"><h5><%= track.get_upvotes.size %></h5></div>
                  <div class="col-xs-4"><i class="fa fa-heart-o" aria-hidden="true"></i></div>
                <% end %>
              </div>
            </div>
          </div>

          <!-- MIDDLE AUDIO PANEL ROW - Play Track -->
          <div class="row middle_audio_panel_row">
              <div class="col-xs-3">
                <div class="text-right play_button_index">
                  <%= link_to track_path(track) do %>
                  <i class="fa fa-play" aria-hidden="true"></i>
                  <% end %>
                </div>
              </div>
              <div class="col-xs-9 text-left track_panel_title">
                <%= link_to track.title, track_path(track) %>
              </div>
          </div>
        <!-- BOTTOM AUDIO PANEL ROW - Artist < > Download -->
        <div class="row bottom_audio_panel_row">
          <div class="col-xs-8">
            <div class="text-left artist_tag">
              <div class="col-xs-2"><%= link_to image_tag track.user.image, class: "audio_panel_profile_image" %></div>
              <div class="col-xs-10 artist_name_h6"><h6 class="text-left"><%= link_to track.user.username, user_path(track.user) %></h6></div>
            </div>
          </div>
          <div class="col-xs-4 text-right download_col">
            <button class="btn download_btn_inner_panel">
              <%= link_to root_path do %>
              <% if track.price == 0 || track.price == nil %>
                FREE | <i class="fa fa-arrow-down" aria-hidden="true"></i>
                <% else %>
              <%= number_to_currency(track.price, unit: "€ ") %> | <i class="fa fa-arrow-down" aria-hidden="true"></i>
              <% end %>
            </button>
          </div>
        </div>
      <% end %>

      </div><!-- end audio_panel -->
      </div><!-- end col-md-4 -->

      <% end %>
      <% end %>

    </div><!-- end audio_panels_display -->
    </div>

    <div id="trending" class="tab-pane fade">
      <div class="container-fluid audio_panels_display">
        <div class="row results_found_row">
          <div class="text-center"><h5><i><%= @tracks.count %> results found</i></h5></div>
        </div>
      <!-- AUDIO PANELS -->
      <% if @tracks.count == 0 %>
        <div class="row result_notice">
          <h3 class="text-center">Sorry! There are currently no new samples in this genre.</h3>
          <div class="text-center"><%= link_to "Add Track for this Genre", new_track_path, class: "btn add_track" %></div>
        </div>
        <% else %>
      <% @tracks.each do |track| %>
      <div class="col-md-4 text-center">
        <!-- AUDIO PANEL -->
        <div class="audio_panel">
          <!-- TOP AUDIO PANEL ROW - Genre < > Likes -->
          <div class="row top_audio_panel_row">
            <div class="col-xs-4 text-left genre_col">
              <button class="btn text-left genre_tag"><%= track.genre.name.upcase %></button>
            </div>
            <div class="col-xs-4 time_ago">
              <p class="text-center"><%= "#{time_ago_in_words(track.created_at).gsub('about ','')} ago" %></p>
            </div>
            <div class="col-xs-4">
              <div class="text-right like_icon">
                <%= link_to like_track_path(track), class: "like", method: :put do %>
                  <div class="col-xs-8"><h5><%= track.get_upvotes.size %></h5></div>
                  <div class="col-xs-4"><i class="fa fa-heart" aria-hidden="true"></i></div>
                <% end %>
              </div>
            </div>
          </div>

          <!-- MIDDLE AUDIO PANEL ROW - Play Track -->
          <div class="row middle_audio_panel_row">
              <div class="col-xs-3">
                <div class="text-right play_button_index">
                  <i class="fa fa-play" aria-hidden="true"></i>
                </div>
              </div>
              <div class="col-xs-9">
                <div class="text-left panel_track_title">
                    <h4><%= link_to track.title, track_path(track) %></h4>
                </div>
              </div>
          </div>

        <!-- BOTTOM AUDIO PANEL ROW - Artist < > Download -->
        <div class="row bottom_audio_panel_row">
          <div class="col-xs-8">
            <div class="text-left artist_tag">
              <div class="col-xs-2"><%= link_to image_tag track.user.user_img, class: "audio_panel_profile_image" %></div>
              <div class="col-xs-10 artist_name_h6"><h6 class="text-left"><%= link_to track.user.username, user_path(track.user) %></h6></div>
            </div>
          </div>
          <div class="col-xs-4 text-right download_col">
            <button class="btn download_btn_inner_panel">
              <%= link_to root_path do %>
              <% if track.price == 0 || track.price == nil %>
                FREE | <i class="fa fa-arrow-down" aria-hidden="true"></i>
                <% else %>
              <%= number_to_currency(track.price, unit: "€ ") %> | <i class="fa fa-arrow-down" aria-hidden="true"></i>
              <% end %>
            </button>
          </div>
        </div>
      <% end %>

      </div><!-- end audio_panel -->
      </div><!-- end col-md-4 -->

      <% end %>
      <% end %>

    </div><!-- end audio_panels_display -->
    </div>
  </div>

</div><!-- end root_index_container -->

<!-- <div class="container-fluid bottom_player">

</div> -->

app/views/tracks/show.html.erb
<%= link_to root_path, class: "btn back_button" do %>
  <i class="fa fa-angle-left fa-3x" aria-hidden="true"></i>
<% end %>

<!-- TRACK SHOW BLOCK -->
<div class="container-fluid">
    <div class="row track_show_title">
      <div class="col-sm-6 title_artist_col">
      <h3 class="text-left"><%= @track.title %></h3>
      <div class="row">
          <h4 class="text-left">By <%= @track.user.username %></h4>
          <h5 class="text-center time_ago_h5"><%= "#{time_ago_in_words(@track.created_at).gsub('about ','')} ago" %></h5>

        <div class="col-xs-9">
          <% if user_signed_in? %>
            <% if @track.user_id == current_user.id %>
          <div class="col-xs-2">
            <%= link_to "Edit", edit_track_path(@track), class: "btn edit_track_btn" %>
          </div>
          <div class="col-xs-2">
            <%= link_to "Delete", track_path(@track), method: :delete, data: { confirm: "Are you sure you want to remove this track from Samplrfy?" }, class: "btn remove_track_btn" %>
          </div>
          <% end %>
        <% end %>
        <div class="col-xs-8">
        </div>
        </div>
      </div>

        <div class="average-review-rating" data-score=<%= @average_review %>></div>


        <div class="how_many">
          <% if @track.reviews.count == nil %>
            <h6>Based on <%= @track.reviews.count %> reviews</h6>
          <% elsif @track.reviews.count == 1 %>
            <h6>Based on <%= @track.reviews.count %> review</h6>
          <% elsif @track.reviews.count > 1 %>
            <h6>Based on <%= @track.reviews.count %> reviews</h6>
          <% end %>
        </div>

    </div>
    <div class="col-sm-6">
      <div class="row">
      </div>
    </div>
  </div><!-- end track_show_title -->
  </div><!-- end container-fluid -->

<!-- REVIEWS AND MORE TRACKS BLOCK -->
    <div class="row comment_options">
        <div class="col-sm-8 reviews_block">
          <div class="col-xs-5 comments_title">
            <h4><%= @track.reviews.count %> Reviews</h4>
          </div>
          <div class="col-xs-7">
            <div class="text-right">
              <%= link_to "Add Review", new_track_review_path(@track), class: "btn review_track_btn" %>
            </div>
          </div>
          <div class="col-sm-12 review_panel">
            <%= render @track.reviews %>
          </div>
        </div><!-- end MAIN col-sm-8 -->


      <div class="col-sm-4 main_col_sm_4 more_tracks_block">
        <div class="row">
          <div class="col-xs-7">
            <div class="text-center">
                <h4>Tracks by <%= @track.user.username %></h4>
            </div>
          </div>

          <div class="col-xs-5">
            <div class="text-center">
              <%= link_to "View Discography", user_path(@track.user), class: "btn view_profile_btn" %>
            </div>
          </div>
        </div>

        <div class="col-xs-12">
          <% @track.user.tracks.each do |track| %>
            <div class="col-xs-9 track_row_in_show">
              <h5><%= link_to track.title, track_path(track) %></h5>
            </div>
            <div class="col-xs-1 save_track_show">
              <div class="text-center">
                <i class="fa fa-plus" aria-hidden="true"></i>
              </div>
            </div>
            <div class="col-xs-2 download_track_show">
              <div class="text-center">
                <i class="fa fa-arrow-down" aria-hidden="true"></i>
              </div>
            </div>
          <% end %>
        </div>
      </div><!-- end MAIN col-sm-4 -->
    </div><!-- end comment_options -->

    <div id="jquery_jplayer_1" class="jp-jplayer"></div>
      <div id="jp_container_1" class="jp-audio" role="application" aria-label="media player">
        <div class="jp-type-single">
          <div class="jp-gui jp-interface">
            <div class="artist_bottom_image">
              <%= image_tag @track.user.image, class: "artist_bottom_image" %>
            </div>
            <div class="jp-controls">
              <button class="jp-play" role="button" tabindex="0">play</button>
              <!-- <button class="jp-stop" role="button" tabindex="0">stop</button> -->
            </div>
            <div class="track_bottom_title">
              <h5><i><%= @track.title %>, by <strong style="font-weight: 300;"><%= @track.user.username %></style></i></h5>
            </div>
            <div class="jp-progress">
              <div class="jp-seek-bar">
                <div class="jp-play-bar"></div>
              </div>
            </div>
            <div class="jp-volume-controls">
              <button class="jp-mute" role="button" tabindex="0">mute</button>
              <button class="jp-volume-max" role="button" tabindex="0">max volume</button>
              <div class="jp-volume-bar">
                <div class="jp-volume-bar-value"></div>
              </div>
            </div>
            <div class="jp-time-holder">
              <div class="jp-current-time" role="timer" aria-label="time">&nbsp;</div>
              <div class="jp-duration" role="timer" aria-label="duration">&nbsp;</div>
              <div class="jp-toggles">
                <button class="jp-repeat" role="button" tabindex="0">repeat</button>
              </div>
            </div>
            <div class="download_bottom_button">
              <button class="btn download_bottom_button_btn">
                <%= link_to root_path do %>
                <% if @track.price == 0 || @track.price == nil %>
                  FREE | <i class="fa fa-arrow-down" aria-hidden="true"></i>
                  <% else %>
                <%= number_to_currency(@track.price, unit: "€ ") %> | <i class="fa fa-arrow-down" aria-hidden="true"></i>
                <% end %>
                <% end %>
              </button>
            </div>
          </div>
          <!--<div class="jp-details">
            <div class="jp-title" aria-label="title">&nbsp;</div>
          </div> -->
          <div class="jp-no-solution">
            <span>Update Required</span>
            To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
          </div>
        </div>
      </div>
  </div>

<!-- Scripts for Raty.js -->
<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

<script>
$('.average-review-rating').raty({
  readOnly: true,
  path: '/assets/',
  score: function() {
    return $(this).attr('data-score');
  }
});
</script>

<script>
  $('#jquery_jplayer_1').jPlayer({
    ready: function () {
      $('#jquery_jplayer_1').jPlayer("setMedia", {
        mp3: "<%= @track.mp3.url %>",
      });
    },
    swfPath: "js",
    supplied: "mp3",
		wmode: "window",
		useStateClassSkin: true,
		autoBlur: false,
		smoothPlayBar: true,
		keyEnabled: true,
		remainingDuration: true,
		toggleDuration: true
  });
</script>